### ISSUE TITLE
mgr. ing.

### ISSUE THREAD

**Issue by nasmeti** [Smidra/titulator#3]
dva tituly stejneho typu se pridavaji pred jmeno podle casu udeleni, vnejsi by mel byt novejsi - tudiz pane magistre

titulator vybral jen inzenyr

**Comment by Smidra** [comment]
Opraveno přidáním iterace nad tituly dokud se nenalezne nějaký titul s ISCED 7.
Skvělý postřeh @nasmeti Děkuji.
