### ISSUE TITLE
peaddr.

### ISSUE THREAD

**Issue by nasmeti** [Smidra/titulator#4]
nerozeznava doktora pedagogiky, psano line (vsechno malym pismem)

**Comment by Smidra** [comment]
Děkuji za nahlášení issues! :1st_place_medal: :smile: 
tituly jsou převádněny do lowercase takže to nehraje roli. Chyba je ve Vašem titulu. Doktor pedagogiky je PaedDr, nikov PeadDr.

![image](https://user-images.githubusercontent.com/25660869/120809251-29889200-c54a-11eb-8464-fe05d7f7a727.png)
